name: Integration Testing
on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: make dep
        working-directory: ./v2
      - name: Build
        run: make
        working-directory: ./v2
      - name: Run integration tests
        run: make itest
        working-directory: ./v2
